# name: Classroom Query and Deploy Automation
# 
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
#   schedule:
#     - cron: '0 */3 * * *'  # 每 3 小时运行一次
#   workflow_dispatch:  # 允许手动触发

# permissions:
#   contents: read
#   pages: write      # 允许部署到 GitHub Pages
#   id-token: write   # 允许对 OIDC 进行身份验证

# concurrency:
#   group: "pages"
#   cancel-in-progress: true

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     
#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '22'
#         
#     - name: Install dependencies
#       run: |
#         npm install
#         npx playwright install chromium
#         
#     - name: Run Playwright test
#       env:
#         YOUR_NEUQ_USERNAME: ${{ secrets.YOUR_NEUQ_USERNAME }}
#         YOUR_NEUQ_PASSWORD: ${{ secrets.YOUR_NEUQ_PASSWORD }}
#       run: npx playwright test tests/classroom_query.spec.ts --project=chromium
#         
#     - name: Process JSON
#       run: node scripts/process_json.js
#         
#     - name: Generate HTML
#       run: node scripts/generate_html.js
#     
#     - name: Setup Pages
#       uses: actions/configure-pages@v5
#       
#     - name: Upload artifact
#       uses: actions/upload-pages-artifact@v3
#       with:
#         # 从根目录上传所有文件
#         path: '.'#

#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     needs: build  # 仅在 build 工作成功后运行
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4